name: CI

on: [push, pull_request]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Deploy
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "iclge-bot"
          email: "m.kaszlewicz@gmail.com"
          dockerfile_path: ${{env.working-directory}}
          formation: "worker"